music.changeTempoBy(178)
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(466, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Whole))
basic.pause(5)
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(466, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Whole))
basic.pause(5)
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(466, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(196, music.beat(BeatFraction.Double))
music.playTone(131, music.beat(BeatFraction.Double))
